# Generated by Django 5.0.1 on 2024-05-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_maincategory_id_alter_medicine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='upload'),
        ),
    ]
